// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsY2dWDvCzcrTezgmEKxEX_72fbeiShU',
    appId: '1:127012041161:web:7952abae14ea0b14cdf818',
    messagingSenderId: '127012041161',
    projectId: 'wallpaper-app-tutorial-8e383',
    authDomain: 'wallpaper-app-tutorial-8e383.firebaseapp.com',
    storageBucket: 'wallpaper-app-tutorial-8e383.appspot.com',
    measurementId: 'G-KQSB7LD74K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWudVnEGYzrEs1LlRowfumDjqFAmpvMQ',
    appId: '1:127012041161:android:fcc5f7778d81e5c9cdf818',
    messagingSenderId: '127012041161',
    projectId: 'wallpaper-app-tutorial-8e383',
    storageBucket: 'wallpaper-app-tutorial-8e383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMWgJ08AIjCail3r8iub3rrIIXtg_UW0',
    appId: '1:127012041161:ios:37f132f1cfabf6d0cdf818',
    messagingSenderId: '127012041161',
    projectId: 'wallpaper-app-tutorial-8e383',
    storageBucket: 'wallpaper-app-tutorial-8e383.appspot.com',
    androidClientId: '127012041161-4qq78g5mveei2nfdschh74gjhtjlujnk.apps.googleusercontent.com',
    iosClientId: '127012041161-rru5lu4k2lua5jc4savcrtjpef6k5nvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMWgJ08AIjCail3r8iub3rrIIXtg_UW0',
    appId: '1:127012041161:ios:2b9940a8ed335f5dcdf818',
    messagingSenderId: '127012041161',
    projectId: 'wallpaper-app-tutorial-8e383',
    storageBucket: 'wallpaper-app-tutorial-8e383.appspot.com',
    androidClientId: '127012041161-4qq78g5mveei2nfdschh74gjhtjlujnk.apps.googleusercontent.com',
    iosClientId: '127012041161-h4o1renhrhaltofpmn312kl13ah11kdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp.RunnerTests',
  );
}
